project_name: mitosu

builds:
  - id: linux-amd64
    main: ./
    goos: [linux]
    goarch: ['amd64']
    env: [CGO_ENABLED=0]
    flags: ['-tags="netgo osusergo"']
    ldflags: ["-s","-w","-X main.BuildDate={{.Date}}","-X main.BuildMode=prod","-X main.BuildCommit={{.Commit}}","-X main.BuildVersion={{.Version}}"]
  - id: linux-386
    main: ./
    goos: [linux]
    goarch: ['386']
    env: [CGO_ENABLED=0]
    flags: ['-tags="netgo osusergo"']
    ldflags: ["-s","-w","-X main.BuildDate={{.Date}}","-X main.BuildMode=prod","-X main.BuildCommit={{.Commit}}","-X main.BuildVersion={{.Version}}"]
  - id: linux-armhf
    main: ./
    goos: [linux]
    goarch: [arm]
    goarm: [7]
    env: [CGO_ENABLED=0]
    flags: ['-tags="netgo osusergo"']
    ldflags: ["-s","-w","-X main.BuildDate={{.Date}}","-X main.BuildMode=prod","-X main.BuildCommit={{.Commit}}","-X main.BuildVersion={{.Version}}"]
  - id: linux-arm64
    main: ./
    goos: [linux]
    goarch: [arm64]
    env: [CGO_ENABLED=0]
    flags: ['-tags="netgo osusergo"']
    ldflags: ["-s","-w","-X main.BuildDate={{.Date}}","-X main.BuildMode=prod","-X main.BuildCommit={{.Commit}}","-X main.BuildVersion={{.Version}}"]
  - id: windows-amd64
    main: ./
    goos: [windows]
    goarch: [amd64]
    env: [CGO_ENABLED=0]
    flags: ['-tags="netgo osusergo"']
    ldflags: ["-s","-w","-X main.BuildDate={{.Date}}","-X main.BuildMode=prod","-X main.BuildCommit={{.Commit}}","-X main.BuildVersion={{.Version}}"]
archives:
  - files:
      - LICENSE
      - README.md
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{- if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{ end }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip

changelog:
  disable: true

checksum:
  name_template: checksums.txt

release:
  github:
    owner: minnowo
    name: mitosu
  draft: true
  prerelease: false
